apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cicd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-cicd-app
  template:
    metadata:
      labels:
        app: python-cicd-app
    spec:
      containers:
      - name: python-container
        image: rmvinay/python-cicd-app:v1
        ports:
        - containerPort: 5000